-- AlterTable
ALTER TABLE `patient` MODIFY `Image` VARCHAR(191) NULL,
    MODIFY `Phone_Number` VARCHAR(191) NULL,
    MODIFY `Patient_Name` VARCHAR(191) NULL,
    MODIFY `Address` VARCHAR(191) NULL,
    MODIFY `Blood_Group` VARCHAR(191) NULL,
    MODIFY `DOB` DATETIME(3) NULL,
    MODIFY `Gender` VARCHAR(191) NULL,
    MODIFY `Registration_Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
